"""initial schema

Revision ID: 9dc740fee984
Revises: 
Create Date: 2026-05-25 07:22:06.177692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9dc740fee984'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=True),
    sa.Column('peso', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratistas',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('calificacion', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('obra_categorias',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('peso', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nombre_corto', sa.String(length=60), nullable=False),
    sa.Column('clave_geo', sa.String(length=10), nullable=False),
    sa.Column('acronimo', sa.String(length=10), nullable=False),
    sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('center', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('polygon_path', sa.String(length=200), nullable=True),
    sa.Column('escudo_path', sa.String(length=200), nullable=True),
    sa.Column('primario', sa.String(length=7), nullable=False),
    sa.Column('secundario', sa.String(length=7), nullable=True),
    sa.Column('dorado', sa.String(length=7), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_geo')
    )
    op.create_table('colonias',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('area_ha', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('viviendas', sa.Integer(), nullable=True),
    sa.Column('densidad', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('codigos_postales', sa.String(length=100), nullable=True),
    sa.Column('servicio_agua', sa.SmallInteger(), nullable=True),
    sa.Column('servicio_drenaje', sa.SmallInteger(), nullable=True),
    sa.Column('servicio_luz', sa.SmallInteger(), nullable=True),
    sa.Column('servicio_internet', sa.SmallInteger(), nullable=True),
    sa.Column('factor_reportes', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colonias_tenant_id'), 'colonias', ['tenant_id'], unique=False)
    op.create_table('cuadrillas',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('integrantes', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuadrillas_tenant_id'), 'cuadrillas', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('iniciales', sa.String(length=5), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_tone', sa.String(length=7), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_tenant_ts', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_user_ts', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('cuadrilla_especialidades',
    sa.Column('cuadrilla_id', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['cuadrillas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cuadrilla_id', 'categoria_id')
    )
    op.create_table('obras',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=15), nullable=False),
    sa.Column('colonia_id', sa.String(length=60), nullable=False),
    sa.Column('colonia_nombre', sa.String(length=120), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('responsable_nombre', sa.String(length=120), nullable=True),
    sa.Column('responsable_iniciales', sa.String(length=5), nullable=True),
    sa.Column('responsable_cargo', sa.String(length=200), nullable=True),
    sa.Column('contratista_id', sa.String(length=10), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin_estimada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avance_pct', sa.SmallInteger(), nullable=False),
    sa.Column('presupuesto_autorizado', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('presupuesto_ejercido', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['obra_categorias.id'], ),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], ),
    sa.ForeignKeyConstraint(['contratista_id'], ['contratistas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index(op.f('ix_obras_tenant_id'), 'obras', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reportes',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('categoria_id', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=10), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('cuadrilla_id', sa.String(length=10), nullable=True),
    sa.Column('colonia_id', sa.String(length=60), nullable=False),
    sa.Column('colonia_nombre', sa.String(length=120), nullable=True),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('peso', sa.SmallInteger(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ciudadano_nombre', sa.String(length=100), nullable=True),
    sa.Column('ciudadano_iniciales', sa.String(length=5), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tiempo_atencion_horas', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.Column('costo_estimado', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('gasto_real', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], ),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['cuadrillas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index('ix_reportes_tenant_categoria', 'reportes', ['tenant_id', 'categoria_id'], unique=False)
    op.create_index('ix_reportes_tenant_estado', 'reportes', ['tenant_id', 'estado'], unique=False)
    op.create_index('ix_reportes_tenant_fecha', 'reportes', ['tenant_id', 'fecha_creacion'], unique=False)
    op.create_index(op.f('ix_reportes_tenant_id'), 'reportes', ['tenant_id'], unique=False)
    op.create_table('user_areas',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('categoria_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'categoria_id')
    )
    op.create_table('obra_calles_afectadas',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('coordenadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin_estimada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alternativas_viales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_calles_afectadas_obra_id'), 'obra_calles_afectadas', ['obra_id'], unique=False)
    op.create_table('obra_documentos',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('tamano_kb', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_documentos_obra_id'), 'obra_documentos', ['obra_id'], unique=False)
    op.create_table('obra_equipo',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('iniciales', sa.String(length=5), nullable=True),
    sa.Column('rol', sa.String(length=60), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_equipo_obra_id'), 'obra_equipo', ['obra_id'], unique=False)
    op.create_table('obra_evidencias',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_evidencias_obra_id'), 'obra_evidencias', ['obra_id'], unique=False)
    op.create_table('obra_presupuesto_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('importe', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_presupuesto_items_obra_id'), 'obra_presupuesto_items', ['obra_id'], unique=False)
    op.create_table('obra_timeline',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('autor_nombre', sa.String(length=120), nullable=True),
    sa.Column('autor_iniciales', sa.String(length=5), nullable=True),
    sa.Column('autor_rol', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obra_timeline_obra_id'), 'obra_timeline', ['obra_id'], unique=False)
    op.create_table('reporte_eventos',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('reporte_id', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('autor_nombre', sa.String(length=100), nullable=True),
    sa.Column('autor_iniciales', sa.String(length=5), nullable=True),
    sa.Column('autor_rol', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_eventos_reporte_id'), 'reporte_eventos', ['reporte_id'], unique=False)
    op.create_table('reporte_evidencias',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('reporte_id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_evidencias_reporte_id'), 'reporte_evidencias', ['reporte_id'], unique=False)
    op.create_table('reporte_obra_relaciones',
    sa.Column('reporte_id', sa.String(length=20), nullable=False),
    sa.Column('obra_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reporte_id', 'obra_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_obra_relaciones')
    op.drop_index(op.f('ix_reporte_evidencias_reporte_id'), table_name='reporte_evidencias')
    op.drop_table('reporte_evidencias')
    op.drop_index(op.f('ix_reporte_eventos_reporte_id'), table_name='reporte_eventos')
    op.drop_table('reporte_eventos')
    op.drop_index(op.f('ix_obra_timeline_obra_id'), table_name='obra_timeline')
    op.drop_table('obra_timeline')
    op.drop_index(op.f('ix_obra_presupuesto_items_obra_id'), table_name='obra_presupuesto_items')
    op.drop_table('obra_presupuesto_items')
    op.drop_index(op.f('ix_obra_evidencias_obra_id'), table_name='obra_evidencias')
    op.drop_table('obra_evidencias')
    op.drop_index(op.f('ix_obra_equipo_obra_id'), table_name='obra_equipo')
    op.drop_table('obra_equipo')
    op.drop_index(op.f('ix_obra_documentos_obra_id'), table_name='obra_documentos')
    op.drop_table('obra_documentos')
    op.drop_index(op.f('ix_obra_calles_afectadas_obra_id'), table_name='obra_calles_afectadas')
    op.drop_table('obra_calles_afectadas')
    op.drop_table('user_areas')
    op.drop_index(op.f('ix_reportes_tenant_id'), table_name='reportes')
    op.drop_index('ix_reportes_tenant_fecha', table_name='reportes')
    op.drop_index('ix_reportes_tenant_estado', table_name='reportes')
    op.drop_index('ix_reportes_tenant_categoria', table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_obras_tenant_id'), table_name='obras')
    op.drop_table('obras')
    op.drop_table('cuadrilla_especialidades')
    op.drop_index('ix_audit_user_ts', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_ts', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cuadrillas_tenant_id'), table_name='cuadrillas')
    op.drop_table('cuadrillas')
    op.drop_index(op.f('ix_colonias_tenant_id'), table_name='colonias')
    op.drop_table('colonias')
    op.drop_table('tenants')
    op.drop_table('obra_categorias')
    op.drop_table('contratistas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
