"""add notificaciones table

Revision ID: bf282849403f
Revises: 9dc740fee984
Create Date: 2026-05-28 03:39:44.784334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf282849403f'
down_revision: Union[str, None] = '9dc740fee984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('href', sa.String(length=300), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=20), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_fecha', 'notificaciones', ['user_id', 'fecha'], unique=False)
    op.create_index('ix_notif_user_leida', 'notificaciones', ['user_id', 'leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tenant_id'), 'notificaciones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_user_id'), 'notificaciones', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_user_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tenant_id'), table_name='notificaciones')
    op.drop_index('ix_notif_user_leida', table_name='notificaciones')
    op.drop_index('ix_notif_user_fecha', table_name='notificaciones')
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
